# Generated by Django 3.2.8 on 2021-11-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
