# Generated by Django 3.2.8 on 2021-11-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatrooms', '0002_message_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='media',
        ),
    ]
